// This file is auto-generated by scripts/build-content-map.ts
// Do not edit manually as changes will be overwritten.

export const contentMap: Record<string, () => number> = {
  'kholagy/basil:ar': () => require('../content/kholagy/basil.ar.md'),
  'kholagy/basil:arcop': () => require('../content/kholagy/basil.arcop.md'),
  'kholagy/basil:cop': () => require('../content/kholagy/basil.cop.md'),
  'kholagy/basil:en': () => require('../content/kholagy/basil.en.md'),
  'kholagy/basil:ru': () => require('../content/kholagy/basil.ru.md'),
};

export type ContentKey = keyof typeof contentMap;
